name: Mirror Repository

on:
  push:
    branches: ["*"]         # Запускается на любой push в любую ветку
  create:
    tags: ["*"]             # При создании тега
  delete:
    tags: ["*"]             # При удалении тега

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # Забираем всю историю
      
      - name: Set up Git config
        run: |
          git config --global user.name "Monte"
          git config --global user.email "mirror-monte@mirror.com"
      
      - name: Push mirror to second repo
        env:
          TARGET_REPO: https://${{ secrets.MIRROR_USERNAME }}:${{ secrets.MIRROR_TOKEN }}@github.com/Monte711/SecurityApp.git
        run: |
          git remote add mirror $TARGET_REPO
          git push --mirror mirror
